### ISSUE TITLE
Improve example usage

### ISSUE THREAD

**Issue by jrosen48** [cddesja/profileR#28]
This pertains to [JOSS review 1941](https://github.com/openjournals/joss-reviews/issues/1941).

Example usage is not documented in the README or paper; there is also not a vignette. Because of this, it may be somewhat challenging for those new to the package to quickly understand how to use the package, and, specifically, because the documentation is primarily specific to each function, how the functions can be used together to carry out a profile analysis.

**Comment by cddesja** [comment]
@okanbulut and I have an unpublished vignette that we're going to submit to https://psyarxiv.com/. @jrosen48, would you like to see an actual example in the paper or would linking to the article there be sufficient?

**Comment by jrosen48** [comment]
I think either would work, and I would be satisfied with either of the options you proposed. My slight preference would be to see a short, worked example (perhaps for the plots that are presented - as-is, it is unclear how they are generated).

Just a question, why is the vignette not published with the package? I think this could be useful!

**Comment by wjakethompson** [comment]
I agree with @jrosen48 that including the vignette within in the package would be helpful. For someone who just finds the package, it is probably easier to open a vignette built into the package. Otherwise, you rely on them finding the README, the JOSS paper, or the psyarxiv paper. In general, my preference is to have as much of the documentation as possible self-contained to improve usability.

If you don't want to publish the vignette in both places, I would at least consider adding a simplified version to the package. I would also recommend including a very minimal example in the README, but would also be fine with a link in the README to a vignette.

**Comment by cddesja** [comment]
@okanbulut added the link to the vignette on the README.md and I'll add the vignette to the package later this week.

**Comment by okanbulut** [comment]
The vignette is now available on the development version of the package on Github.

**Comment by cddesja** [comment]
And the vignette can be accessed via the package on GitHub (and CRAN once tests are added) via:
```r
vignette("profiler-vignette")
```
